name: Build Flutter APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: subosito/flutter-action@main
        with:
          flutter-version: '3.24.x'
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: scholar-apk
          path: build/app/outputs/flutter-apk/*.apk
